# GitLeaks configuration for Docker Claude Sandbox
# Excludes false positives for documentation and setup guides

title = "GitLeaks Config for Docker Claude Sandbox"

[extend]
# Use default GitLeaks rules
useDefault = true

[[rules]]
description = "Docker Personal Access Token"
id = "docker-pat"
regex = '''dckr_pat_[a-zA-Z0-9]{36}'''
keywords = ["dckr_pat"]

# Allowlisted patterns for documentation
[allowlist]
description = "Allowlisted files and patterns"
files = [
    '''DOCKER_HUB_SETUP\.md''',   # Setup documentation can reference token format
    '''AI_DEVELOPMENT_GUIDE\.md''', # AI guide can show examples
    '''\.github/workflows/.*\.yml''', # Workflow files use secrets references
]
paths = [
    '''gitleaks-report\.json''',  # GitLeaks report files
]
regexes = [
    '''YOUR_DOCKER_TOKEN''',  # Placeholder token in documentation
    '''dckr_pat_XXXXXXXXXX''',  # Example token format in documentation
    '''\$\{\{ secrets\.DOCKERHUB_TOKEN \}\}''',  # GitHub Actions secrets syntax
]