services: 
  claude-sandbox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE=workspace
    # container_name is set dynamically by run.sh
    hostname: claude-sandbox
    stdin_open: true
    tty: true
    working_dir: /workspace
    volumes:
      - claude_sandbox_data:/workspace
    environment:
      - TERM=xterm-256color
      - CONTAINER_NAME=claude-sandbox
      - TZ=${TZ:-UTC}
    # Resource limits for safety (2GB RAM, 2 CPU cores)
    mem_limit: 2g
    memswap_limit: 2g
    cpus: 2.0
volumes:
  claude_sandbox_data:
    external: true
    name: ${CONTAINER_NAME:-claude-sandbox}_data