name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get version from VERSION file
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT
        
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v${{ steps.version.outputs.VERSION }}
          body: |
            ## 🚀 Docker Claude Sandbox v${{ steps.version.outputs.VERSION }}
            
            ### Installation
            ```bash
            # Quick install
            curl -fsSL https://raw.githubusercontent.com/nixfred/docker-claude-sandbox/main/run.sh | bash
            
            # Version-specific install
            curl -fsSL https://raw.githubusercontent.com/nixfred/docker-claude-sandbox/v${{ steps.version.outputs.VERSION }}/run.sh | bash
            ```
            
            ### What's Changed
            See [CHANGELOG.md](https://github.com/nixfred/docker-claude-sandbox/blob/v${{ steps.version.outputs.VERSION }}/changelog.md) for details.
            
            ### Full Documentation
            - [README](https://github.com/nixfred/docker-claude-sandbox/blob/v${{ steps.version.outputs.VERSION }}/readme.md)
            - [Technical Guide](https://github.com/nixfred/docker-claude-sandbox/blob/v${{ steps.version.outputs.VERSION }}/claude.md)
          draft: false
          prerelease: false